# Generated by Django 4.1.3 on 2022-12-07 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название блюда')),
                ('text', models.TextField(verbose_name='текст')),
                ('heading', models.CharField(choices=[('SN', 'Закуска'), ('FC', 'Первое блюдо'), ('SC', 'Второе блюдо'), ('BK', 'Выпечка'), ('MR', 'Маринад'), ('PT', 'Напитки'), ('SS', 'Приправа'), ('DT', 'Десерт'), ('SC', 'Соус')], max_length=2, verbose_name='рубрика')),
                ('cooking_time', models.FloatField(blank=True, null=True, verbose_name='время приготовления')),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='фото блюда')),
                ('serving', models.IntegerField(verbose_name='порции')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='опубликовано')),
                ('edited_at', models.DateField(auto_now=True, verbose_name='изменено')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='кол-во просмотров')),
                ('slug', models.SlugField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='слаг')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'db_table': 'recipe',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipeCountViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=150)),
                ('recipe_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56, verbose_name='имя')),
                ('last_name', models.CharField(max_length=56, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='электронная почта')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='никнейм')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images/profile/', verbose_name='фото пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profile',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1500, verbose_name='комментарий')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='опубликовано')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_recipe', to='app_blog.recipe')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
            },
        ),
    ]
